spring:
  application:
    name: lab2_jwt
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:postgresql://localhost:5432/lab2_Oweb
    username: postgres
    password: 1337
    driver-class-name: org.postgresql.Driver
